server:
  port: 8083

spring:
  application:
    name: task3-clash-detection

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017}
      database: ${MONGO_DATABASE:idss}

task3:
  input:
    enrollments-path: ${TASK3_ENROLLMENTS_PATH:../data/input/input_student_enrollments.json}
    exams-path: ${TASK3_EXAMS_PATH:../data/input/input_exams.json}
