package com.idss.task1.controller;

import com.idss.common.util.JsonLoader;
import com.idss.task1.model.DeliveryRoute;
import com.idss.task1.model.DispatchOrder;
import com.idss.task1.model.RoutingMetrics;
import com.idss.task1.repository.DeliveryRouteRepository;
import com.idss.task1.service.RouteService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * REST API for Task 1 route computation and retrieval (Student B Deliverable - Subtask 4.5).
 * Exposed to the frontend via the Gateway at {@code http://localhost:8080/api/task1/**}
 * (master_context_file.md Section 3.4).
 */
@RestController
@RequestMapping("/api/task1")
public class RouteController {

    private static final Logger log = LoggerFactory.getLogger(RouteController.class);

    private final RouteService routeService;
    private final DeliveryRouteRepository deliveryRouteRepository;
    private final String outputMetricsPath;

    public RouteController(RouteService routeService,
                            DeliveryRouteRepository deliveryRouteRepository,
                            @Value("${idss.task1.output-metrics-path:data/shared/output_routing_metrics.json}") String outputMetricsPath) {
        this.routeService = routeService;
        this.deliveryRouteRepository = deliveryRouteRepository;
        this.outputMetricsPath = outputMetricsPath;
    }

    /**
     * Computes optimal routes for the given dispatch orders (or the default input file
     * when the body is null/empty), persists them to MongoDB, and returns the result.
     * Returns HTTP 422 when any dispatch fails a hard constraint (master_context_file.md
     * Section 3.4: "HTTP 422 = hard constraint violated").
     */
    @PostMapping("/route")
    public ResponseEntity<Map<String, Object>> computeRoutes(@RequestBody(required = false) List<DispatchOrder> dispatchOrders) {
        Map<String, Object> result = routeService.processDispatches(dispatchOrders);
        persistRoutes(result);

        boolean allOptimal = "OPTIMAL".equals(result.get("status"));
        HttpStatus status = allOptimal ? HttpStatus.OK : HttpStatus.UNPROCESSABLE_ENTITY;
        return ResponseEntity.status(status).body(result);
    }

    /**
     * Retrieves a previously computed and persisted route by dispatch ID.
     */
    @GetMapping("/routes/{dispatchId}")
    public ResponseEntity<DeliveryRoute> getRoute(@PathVariable String dispatchId) {
        Optional<DeliveryRoute> route = deliveryRouteRepository.findById(dispatchId);
        return route.map(ResponseEntity::ok).orElseGet(() -> ResponseEntity.notFound().build());
    }

    /**
     * Returns the latest empirical benchmark metrics generated by the Step 5 benchmark
     * suite. 404 if no benchmark run has produced {@code output_routing_metrics.json} yet.
     */
    @GetMapping("/benchmark")
    public ResponseEntity<RoutingMetrics> getBenchmark() {
        try {
            RoutingMetrics metrics = JsonLoader.load(outputMetricsPath, RoutingMetrics.class);
            return ResponseEntity.ok(metrics);
        } catch (Exception e) {
            log.warn("No benchmark metrics available at '{}': {}", outputMetricsPath, e.getMessage());
            return ResponseEntity.notFound().build();
        }
    }

    /** Service health check. */
    @GetMapping("/health")
    public ResponseEntity<Map<String, String>> health() {
        return ResponseEntity.ok(Map.of("status", "UP"));
    }

    /**
     * Persists computed routes to MongoDB. Failures are logged but never fail the HTTP
     * response — route computation must not be blocked by database availability
     * (master_context_file.md Section 2.4).
     */
    @SuppressWarnings("unchecked")
    private void persistRoutes(Map<String, Object> result) {
        Object routesObj = result.get("routes");
        if (!(routesObj instanceof List<?> routesList) || routesList.isEmpty()) {
            return;
        }
        try {
            deliveryRouteRepository.saveAll((List<DeliveryRoute>) routesObj);
        } catch (Exception e) {
            log.warn("Failed to persist delivery routes to MongoDB (routes still returned to caller): {}", e.getMessage());
        }
    }
}
