server:
  port: 8082

task2:
  input:
    invigilators-path: ${TASK2_INVIGILATORS_PATH:../data/input/input_invigilators.json}
    schedule-path: ${TASK2_SCHEDULE_PATH:../data/shared/output_master_schedule.json}
  output:
    roster-path: ${TASK2_ROSTER_PATH:../data/shared/output_proctor_roster.json}
    metrics-path: ${TASK2_METRICS_PATH:../data/shared/output_roster_metrics.json}
